// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPPizza.Web.DataAccessLayer;

#nullable disable

namespace TPPizza.Web.Migrations
{
    [DbContext(typeof(PizzeriaDbContext))]
    [Migration("20240716133013_SeedDoughAndIngredients")]
    partial class SeedDoughAndIngredients
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaIngredients", b =>
                {
                    b.Property<long>("PizzaId")
                        .HasColumnType("bigint");

                    b.Property<long>("IngredientId")
                        .HasColumnType("bigint");

                    b.HasKey("PizzaId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("PizzaIngredients");
                });

            modelBuilder.Entity("TPPizza.Web.DataAccessLayer.Entity.Dough", b =>
                {
                    b.Property<long>("DoughId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("DoughId"));

                    b.Property<string>("DoughName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("DoughId");

                    b.ToTable("Doughs");

                    b.HasData(
                        new
                        {
                            DoughId = 1L,
                            DoughName = "Neapolitan"
                        },
                        new
                        {
                            DoughId = 2L,
                            DoughName = "New York Style"
                        },
                        new
                        {
                            DoughId = 3L,
                            DoughName = "Chicago Deep Dish"
                        },
                        new
                        {
                            DoughId = 4L,
                            DoughName = "Sicilian"
                        },
                        new
                        {
                            DoughId = 5L,
                            DoughName = "Whole Wheat"
                        },
                        new
                        {
                            DoughId = 6L,
                            DoughName = "Gluten-Free"
                        },
                        new
                        {
                            DoughId = 7L,
                            DoughName = "Sourdough"
                        },
                        new
                        {
                            DoughId = 8L,
                            DoughName = "Cauliflower"
                        });
                });

            modelBuilder.Entity("TPPizza.Web.DataAccessLayer.Entity.Ingredient", b =>
                {
                    b.Property<long>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("IngredientId"));

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1L,
                            IngredientName = "Tomato Sauce"
                        },
                        new
                        {
                            IngredientId = 2L,
                            IngredientName = "Mozzarella Cheese"
                        },
                        new
                        {
                            IngredientId = 3L,
                            IngredientName = "Pepperoni"
                        },
                        new
                        {
                            IngredientId = 4L,
                            IngredientName = "Mushrooms"
                        },
                        new
                        {
                            IngredientId = 5L,
                            IngredientName = "Bell Peppers"
                        },
                        new
                        {
                            IngredientId = 6L,
                            IngredientName = "Onions"
                        },
                        new
                        {
                            IngredientId = 7L,
                            IngredientName = "Olives"
                        },
                        new
                        {
                            IngredientId = 8L,
                            IngredientName = "Sausage"
                        },
                        new
                        {
                            IngredientId = 9L,
                            IngredientName = "Ham"
                        },
                        new
                        {
                            IngredientId = 10L,
                            IngredientName = "Pineapple"
                        },
                        new
                        {
                            IngredientId = 11L,
                            IngredientName = "Bacon"
                        },
                        new
                        {
                            IngredientId = 12L,
                            IngredientName = "Spinach"
                        },
                        new
                        {
                            IngredientId = 13L,
                            IngredientName = "Garlic"
                        },
                        new
                        {
                            IngredientId = 14L,
                            IngredientName = "Basil"
                        },
                        new
                        {
                            IngredientId = 15L,
                            IngredientName = "Ricotta Cheese"
                        });
                });

            modelBuilder.Entity("TPPizza.Web.DataAccessLayer.Entity.Pizza", b =>
                {
                    b.Property<long>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PizzaId"));

                    b.Property<long>("DoughId")
                        .HasColumnType("bigint");

                    b.Property<string>("PizzaName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PizzaId");

                    b.HasIndex("DoughId");

                    b.HasIndex("PizzaName")
                        .IsUnique();

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("PizzaIngredients", b =>
                {
                    b.HasOne("TPPizza.Web.DataAccessLayer.Entity.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TPPizza.Web.DataAccessLayer.Entity.Pizza", null)
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TPPizza.Web.DataAccessLayer.Entity.Pizza", b =>
                {
                    b.HasOne("TPPizza.Web.DataAccessLayer.Entity.Dough", "Dough")
                        .WithMany("Pizzas")
                        .HasForeignKey("DoughId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dough");
                });

            modelBuilder.Entity("TPPizza.Web.DataAccessLayer.Entity.Dough", b =>
                {
                    b.Navigation("Pizzas");
                });
#pragma warning restore 612, 618
        }
    }
}
